CREATE TABLE IF NOT EXISTS "users" (
    "id" UUID NOT NULL,
    "username" VARCHAR(255) NOT NULL DEFAULT '',
    "email" VARCHAR(50) DEFAULT '',
    "password" TEXT DEFAULT '',
    "created_at" TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);